seed_everything: 123
trainer:
  logger: 
    class_path: pytorch_lightning.loggers.WandbLogger
  checkpoint_callback: false
  callbacks: 
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: 'val_loss'
        patience: 15
        divergence_threshold: 1000.0 
  default_root_dir: null
  gradient_clip_val: 0.0
  gradient_clip_algorithm: norm
  process_position: 0
  num_nodes: 1
  num_processes: 1
  gpus: 1
  auto_select_gpus: false
  tpu_cores: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 100
  min_epochs: null
  max_steps: null
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  flush_logs_every_n_steps: 100
  log_every_n_steps: 50
  accelerator: null
  sync_batchnorm: false
  precision: 32
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  truncated_bptt_steps: null
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: true
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: true
  terminate_on_nan: false
  auto_scale_batch_size: false
  prepare_data_per_node: true
  plugins: null
  amp_backend: native
  amp_level: O2
  distributed_backend: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
model:
  # possible models: see model.py
  # resnet18, vgg11, simple_conv, depth_conv
  model_name: 'depth_conv'
  # for SimpleConvNet
  kernel_size: 3
  conv_layers: [16, 32]
  depth: 5
  # NOTE: this is only relevant for the deepee DP tool
  # possible surgeries: see surgery.py
  # NOTE: comment out if not needed
  # model_surgeon: 
  #   class_path: deepee.ModelSurgeon
  #   init_args:
  #     converter: utils.BN_to_GN
  data_name: 'cifar10'
  # possible optims: sgd, adam
  optimizer: 'sgd'
  opt_kwargs: 
    lr: 0.05
    # optional
    momentum: 0.0
    weight_decay: 0.0
  lr_scheduler: false
  batch_size: 32
  virtual_batch_size: 0 # not using at the moment
  dp_tool: "opacus"
  dp: true
  # NOTE: already set in sweep config
  # L2_clip: 1.677 
  # noise_multiplier: 0.5216 
  target_epsilon: 10.0
  abort: true
  target_delta: 1e-5
  fallback_to_rdp: false
data:
  # possible datasets: cifar10, fashion_mnist, imagenet, mnist
  # name: 'cifar10' 
  data_dir: './data'
  val_split: 0.2
  num_workers: 16
  normalize: true
  seed: 42
  shuffle: false
  pin_memory: false
  drop_last: false
  train_transforms: null
  val_transforms: null
  test_transforms: null
  dims: null