absl-py==0.13.0
aiohttp==3.7.4.post0
argon2-cffi==20.1.0
async-generator==1.10
async-timeout==3.0.1
attrs==21.2.0
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
bleach==4.0.0
cachetools==4.2.2
captum==0.4.0
certifi==2021.5.30
cffi==1.14.6
chardet==4.0.0
click==8.0.1
cloudpickle==1.6.0
configparser==5.0.2
cycler==0.10.0
decorator @ file:///tmp/build/80754af9/decorator_1621259047763/work
deepee==0.1.9
defusedxml==0.7.1
docker-pycreds==0.4.0
docstring-parser==0.10
entrypoints==0.3
fsspec==2021.6.1
future==0.18.2
gitdb==4.0.7
GitPython==3.1.18
google-auth==1.32.0
google-auth-oauthlib==0.4.4
grpcio==1.38.1
gym==0.18.3
idna==2.10
ipykernel @ file:///tmp/build/80754af9/ipykernel_1596207638929/work/dist/ipykernel-5.3.4-py3-none-any.whl
ipython @ file:///tmp/build/80754af9/ipython_1628243924020/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipywidgets==7.6.3
jedi @ file:///tmp/build/80754af9/jedi_1611333125342/work
Jinja2==3.0.1
joblib==1.0.1
jsonargparse==3.17.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1616770841739/work
jupyter-console==6.4.0
jupyter-core @ file:///tmp/build/80754af9/jupyter_core_1612213311222/work
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
kiwisolver==1.3.1
Markdown==3.3.4
MarkupSafe==2.0.1
matplotlib==3.4.2
matplotlib-inline @ file:///tmp/build/80754af9/matplotlib-inline_1628242447089/work
mistune==0.8.4
multidict==5.1.0
mypy==0.910
mypy-extensions==0.4.3
nbclient==0.5.3
nbconvert==6.1.0
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.4.3
numpy==1.21.0
oauthlib==3.1.1
opacus==0.14.0
packaging==20.9
pandas==1.3.1
pandocfilters==1.4.3
parso @ file:///tmp/build/80754af9/parso_1617223946239/work
pathtools==0.1.2
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow==8.2.0
prometheus-client==0.11.0
promise==2.3
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1616415428029/work
protobuf==3.17.3
psutil==5.8.0
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pyDeprecate==0.3.0
pyglet==1.5.15
Pygments @ file:///tmp/build/80754af9/pygments_1621606182707/work
pyparsing==2.4.7
pyrsistent==0.18.0
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
pytorch-lightning==1.3.8
pytorch-lightning-bolts==0.3.2
pytorchcv==0.0.67
pytz==2021.1
PyYAML==5.4.1
pyzmq @ file:///tmp/build/80754af9/pyzmq_1628276010766/work
qtconsole==5.1.1
QtPy==1.9.0
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7.2
scikit-learn==0.24.2
scipy==1.7.0
Send2Trash==1.8.0
sentry-sdk==1.1.0
shortuuid==1.0.1
six @ file:///tmp/build/80754af9/six_1623709665295/work
sklearn==0.0
smmap==4.0.0
subprocess32==3.5.4
tensorboard==2.4.1
tensorboard-plugin-wit==1.8.0
terminado==0.11.0
testpath==0.5.0
threadpoolctl==2.1.0
timm==0.4.12
toml==0.10.2
torch==1.8.0+cu101
torch-tb-profiler==0.2.1
torchcsprng==0.2.0+cu101
torchmetrics==0.3.2
torchvision==0.9.0+cu101
tornado @ file:///tmp/build/80754af9/tornado_1606942300299/work
tqdm==4.61.1
traitlets @ file:///home/ktietz/src/ci/traitlets_1611929699868/work
typing-extensions==3.10.0.0
urllib3==1.26.5
Wand==0.6.6
wandb==0.12.0
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
Werkzeug==2.0.1
widgetsnbextension==3.5.1
yarl==1.6.3
